- src: artis3n.tailscale
- src: geerlingguy.docker
- src: geerlingguy.security
- src: geerlingguy.ntp
- src: geerlingguy.github-users
- src: grog.package
- src: rossmcdonald.telegraf
- src: ironicbadger.docker_compose_generator
- src: ironicbadger.bash_aliases
- src: ironicbadger.figurine
- src: ironicbadger.apprise_boot_notification
- src: ironicbadger.hddtemp
- src: ironicbadger.snapraid
- src: ironicbadger.proxmox_nag_removal

- src: git+https://github.com/c0sco/ansible-modules-bitwarden
- src: weareinteractive.environment

# - src: geerlingguy.docker
# - src: geerlingguy.security
# - src: ironicbadger.ansible_role_create_users
# - src: ironicbadger.ansible_role_docker_compose_generator
# - src: ironicbadger.ansible_role_snapraid
# - src: ironicbadger.ansible_role_nginx_configs
# - src: ironicbadger.ansible_role_hddtemp
# - src: ironicbadger.ansible_role_packages
# - src: rossmcdonald.telegraf
# - src: ironicbadger.ansible_role_bash_aliases
# - src: grog.package
# - src: ironicbadger.ansible_users
# - src: weareinteractive.environment
# - src: geerlingguy.ntp
# - src: ssh://git@git.ktz.me:2222/alexktz/ansible-role-ktz-rh-vpn.git
#   scm: git
#   name: ktz-rh-vpn
# - src: ssh://git@git.ktz.me:2222/alexktz/ansible-role-ktz-apcupsd.git
#   scm: git
#   name: ktz-apcupsd