---

- name: sanoid setup
  include: sanoid.yaml
  tags:
    - sanoid
  when: sanoid_build_from_source

# todo remove this hack
- name: ensure sanoid is installed
  apt:
    name: sanoid
    state: present
  ignore_errors: True

- name: replication setup
  include: replication.yaml
  tags:
    - replication

- name: Give user passwordless access to ZFS commands
  lineinfile:
    path: /etc/sudoers
    line: "{{ main_username }} ALL=(ALL) NOPASSWD: /usr/sbin/zfs,/usr/sbin/zpool"
  become: true

- debug:
    msg: "{{ lookup('bitwarden', '09767edf-04e7-4d0c-9e10-ab420111b486') }}"
  tags: bw
